apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bank-vaults-secret-access
  namespace: vault
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
    - "vault-unseal-keys"
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [""]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bank-vaults-secret-access
  namespace: vault
roleRef:
  kind: Role
  name: bank-vaults-secret-access
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault