apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kong-gateway-proxy
  namespace: kong
spec:
  commonName: cluster.local
  dnsNames:
    - '*.cluster.local'
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
  renewBefore: 360h0m0s
  secretName: kong-gateway-proxy-cert