# certificate used for vault internal communication
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  duration: 30d
  renewBefore: 14d
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - server auth
    - client auth
  commonName: vault.vault
  dnsNames:
    - "vault.vault"
    - "vault.vault.svc"
    - "vault.vault.svc.cluster.local"
    - "*.vault-internal"
    - "*.vault-internal.vault"
    - "*.vault-internal.vault.svc"
    - "*.vault-internal.vault.svc.cluster.local"
